# Generated by Django 6.0.2 on 2026-02-20 12:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('shop_id', models.CharField(editable=False, max_length=50, primary_key=True, serialize=False)),
                ('shop_name', models.CharField(max_length=100, verbose_name='店铺名称')),
                ('account', models.CharField(max_length=100, verbose_name='登录账号')),
                ('password', models.CharField(max_length=255, verbose_name='登录密码')),
                ('login_url', models.URLField(blank=True, max_length=500, verbose_name='登录地址')),
                ('platform_type', models.CharField(choices=[('taobao', '淘宝/天猫'), ('jd', '京东'), ('pdd', '拼多多'), ('douyin', '抖音'), ('kuaishou', '快手'), ('xianyu', '闲鱼'), ('wechat', '微信'), ('xiaohongshu', '小红书'), ('other', '其他')], default='taobao', max_length=20, verbose_name='平台类型')),
                ('status', models.CharField(choices=[('inactive', '未启动'), ('running', '运行中'), ('stopped', '已停止')], default='inactive', max_length=20, verbose_name='状态')),
                ('config_json', models.JSONField(blank=True, default=dict, verbose_name='配置')),
                ('notes', models.TextField(blank=True, verbose_name='备注/知识库')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='最后登录')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shops', to=settings.AUTH_USER_MODEL, verbose_name='所有者')),
            ],
            options={
                'verbose_name': '店铺',
                'verbose_name_plural': '店铺',
                'db_table': 'shops',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['owner', 'platform_type'], name='shops_owner_i_730e9e_idx'), models.Index(fields=['status'], name='shops_status_a77d69_idx')],
            },
        ),
    ]
