# Generated by Django 6.0.2 on 2026-02-20 12:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuickReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='标题')),
                ('content', models.TextField(verbose_name='回复内容')),
                ('shortcut', models.CharField(blank=True, max_length=20, verbose_name='快捷键')),
                ('category', models.CharField(choices=[('greeting', '问候语'), ('logistics', '物流相关'), ('refund', '退款退货'), ('after_sales', '售后服务'), ('product', '商品咨询'), ('promotion', '优惠活动'), ('other', '其他')], default='other', max_length=20, verbose_name='分类')),
                ('usage_count', models.IntegerField(default=0, verbose_name='使用次数')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quick_replies', to=settings.AUTH_USER_MODEL, verbose_name='所属用户')),
            ],
            options={
                'verbose_name': '快捷回复',
                'verbose_name_plural': '快捷回复',
                'db_table': 'quick_replies',
                'ordering': ['sort_order', '-usage_count', '-created_at'],
                'indexes': [models.Index(fields=['user', 'category'], name='quick_repli_user_id_94d6c9_idx'), models.Index(fields=['shortcut'], name='quick_repli_shortcu_f26460_idx')],
                'unique_together': {('user', 'shortcut')},
            },
        ),
    ]
