# Generated by Django 6.0.2 on 2026-02-21 16:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shops', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer_message', models.TextField(verbose_name='买家消息')),
                ('customer_reply', models.TextField(verbose_name='客服回复')),
                ('conversation_context', models.TextField(blank=True, default='', verbose_name='对话上下文')),
                ('buyer_name', models.CharField(blank=True, default='', max_length=100, verbose_name='买家名称')),
                ('image_analysis', models.TextField(blank=True, default='', verbose_name='图片分析结果')),
                ('order_info', models.TextField(blank=True, default='', verbose_name='订单信息')),
                ('platform', models.CharField(blank=True, default='', max_length=20, verbose_name='平台')),
                ('source', models.CharField(choices=[('ai_auto', 'AI自动回复'), ('ai_kb', '知识库匹配回复'), ('human_edited', '人工编辑回复'), ('debug_edited', '调试编辑回复')], default='ai_auto', max_length=20, verbose_name='回复来源')),
                ('quality', models.CharField(choices=[('unverified', '未验证'), ('approved', '已确认'), ('rejected', '已拒绝')], default='unverified', max_length=20, verbose_name='质量标记')),
                ('model_used', models.CharField(blank=True, default='', max_length=50, verbose_name='使用模型')),
                ('confidence', models.FloatField(default=0.0, verbose_name='置信度')),
                ('used_for_training', models.BooleanField(default=False, verbose_name='已用于训练')),
                ('exported', models.BooleanField(default=False, verbose_name='已导出')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conversation_records', to=settings.AUTH_USER_MODEL, verbose_name='所有者')),
                ('shop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conversation_records', to='shops.shop', verbose_name='所属店铺')),
            ],
            options={
                'verbose_name': '对话记录',
                'verbose_name_plural': '对话记录',
                'db_table': 'ai_conversation_records',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['shop', 'quality'], name='ai_conversa_shop_id_cffb84_idx'), models.Index(fields=['source'], name='ai_conversa_source_b60ad5_idx'), models.Index(fields=['quality', 'used_for_training'], name='ai_conversa_quality_c34bdc_idx'), models.Index(fields=['created_at'], name='ai_conversa_created_ae23c2_idx')],
            },
        ),
        migrations.CreateModel(
            name='LearningRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_type', models.CharField(choices=[('product_knowledge', '商品知识'), ('qa_pair', '问答对'), ('image_description', '图片描述')], default='product_knowledge', max_length=30, verbose_name='记录类型')),
                ('instruction', models.TextField(verbose_name='指令/问题')),
                ('response', models.TextField(verbose_name='回答/知识')),
                ('product_name', models.CharField(blank=True, default='', max_length=255, verbose_name='商品名称')),
                ('raw_knowledge', models.TextField(blank=True, default='', verbose_name='原始学习内容')),
                ('used_for_training', models.BooleanField(default=False, verbose_name='已用于训练')),
                ('exported', models.BooleanField(default=False, verbose_name='已导出')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='learning_records', to=settings.AUTH_USER_MODEL, verbose_name='所有者')),
                ('shop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='learning_records', to='shops.shop', verbose_name='所属店铺')),
            ],
            options={
                'verbose_name': '学习记录',
                'verbose_name_plural': '学习记录',
                'db_table': 'ai_learning_records',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['shop', 'record_type'], name='ai_learning_shop_id_754396_idx'), models.Index(fields=['used_for_training'], name='ai_learning_used_fo_f21799_idx')],
            },
        ),
    ]
