# Generated by Django 6.0.2 on 2026-02-22 03:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0001_initial'),
        ('shops', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KeywordRule',
            fields=[
                ('rule_id', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='规则ID')),
                ('name', models.CharField(max_length=100, verbose_name='规则名称')),
                ('platform', models.CharField(blank=True, choices=[('', '所有平台'), ('taobao', '淘宝/千牛'), ('pdd', '拼多多'), ('douyin', '抖音')], default='', max_length=20, verbose_name='适用平台')),
                ('keywords', models.TextField(help_text='每行一个关键词', verbose_name='关键词')),
                ('match_type', models.CharField(choices=[('contains', '包含任意'), ('equals', '完全匹配'), ('all_contains', '包含所有')], default='contains', max_length=20, verbose_name='匹配方式')),
                ('reply_text', models.TextField(verbose_name='预设回复')),
                ('reply_image', models.CharField(blank=True, default='', max_length=500, verbose_name='回复图片路径')),
                ('priority', models.IntegerField(default=0, verbose_name='优先级')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='keyword_rules', to=settings.AUTH_USER_MODEL, verbose_name='所有者')),
                ('shop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='keyword_rules', to='shops.shop', verbose_name='所属店铺')),
            ],
            options={
                'verbose_name': '关键词规则',
                'verbose_name_plural': '关键词规则',
                'db_table': 'keyword_rules',
                'ordering': ['-priority', '-created_at'],
                'indexes': [models.Index(fields=['shop', 'is_active'], name='keyword_rul_shop_id_41633e_idx')],
            },
        ),
        migrations.CreateModel(
            name='ScenarioRule',
            fields=[
                ('rule_id', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='规则ID')),
                ('name', models.CharField(max_length=100, verbose_name='规则名称')),
                ('platform', models.CharField(blank=True, choices=[('', '所有平台'), ('taobao', '淘宝/千牛'), ('pdd', '拼多多'), ('douyin', '抖音')], default='', max_length=20, verbose_name='适用平台')),
                ('scenario_type', models.CharField(choices=[('angry', '客户愤怒'), ('complaint', '投诉举报'), ('urgent', '紧急问题'), ('night_message', '深夜消息'), ('refund_request', '退款请求'), ('custom', '自定义')], default='custom', max_length=20, verbose_name='情景类型')),
                ('detection_method', models.CharField(choices=[('ai_judge', 'AI判断'), ('keyword', '关键词匹配'), ('time_based', '时间条件')], default='ai_judge', max_length=20, verbose_name='检测方式')),
                ('trigger_condition', models.JSONField(default=dict, help_text='AI判断: {"prompt": "..."}, 关键词: {"keywords": [...]}, 时间: {"start_hour": 22, "end_hour": 6}', verbose_name='触发条件')),
                ('action_type', models.CharField(choices=[('transfer_human', '转人工客服'), ('send_reply', '发送特定回复'), ('no_auto_reply', '不自动回复'), ('notify_only', '仅通知')], default='notify_only', max_length=20, verbose_name='触发动作')),
                ('action_config', models.JSONField(default=dict, help_text='{"reply_template": "...", "notify_title": "..."}', verbose_name='动作配置')),
                ('priority', models.IntegerField(default=0, verbose_name='优先级')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('trigger_count', models.IntegerField(default=0, verbose_name='触发次数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scenario_rules', to=settings.AUTH_USER_MODEL, verbose_name='所有者')),
                ('shop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scenario_rules', to='shops.shop', verbose_name='所属店铺')),
            ],
            options={
                'verbose_name': '情景规则',
                'verbose_name_plural': '情景规则',
                'db_table': 'scenario_rules',
                'ordering': ['-priority', '-created_at'],
                'indexes': [models.Index(fields=['shop', 'is_active'], name='scenario_ru_shop_id_c0b600_idx'), models.Index(fields=['scenario_type'], name='scenario_ru_scenari_38b560_idx')],
            },
        ),
        migrations.CreateModel(
            name='SensitiveWordRule',
            fields=[
                ('rule_id', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='规则ID')),
                ('name', models.CharField(blank=True, default='', max_length=100, verbose_name='规则名称')),
                ('platform', models.CharField(blank=True, choices=[('', '所有平台'), ('taobao', '淘宝/千牛'), ('pdd', '拼多多'), ('douyin', '抖音')], default='', max_length=20, verbose_name='适用平台')),
                ('sensitive_words', models.TextField(help_text='每行一个敏感词', verbose_name='敏感词')),
                ('replacement', models.CharField(default='***', max_length=100, verbose_name='替换词')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sensitive_word_rules', to=settings.AUTH_USER_MODEL, verbose_name='所有者')),
                ('shop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sensitive_word_rules', to='shops.shop', verbose_name='所属店铺')),
            ],
            options={
                'verbose_name': '敏感词规则',
                'verbose_name_plural': '敏感词规则',
                'db_table': 'sensitive_word_rules',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['shop', 'is_active'], name='sensitive_w_shop_id_0f1f63_idx')],
            },
        ),
    ]
