# Generated by Django 6.0.2 on 2026-02-23 04:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0002_add_keyword_sensitive_scenario_rules'),
        ('shops', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keywordrule',
            name='platform',
            field=models.CharField(blank=True, choices=[('', '所有平台'), ('taobao', '淘宝/千牛'), ('pdd', '拼多多'), ('douyin', '抖音'), ('wechat', '微信')], default='', max_length=20, verbose_name='适用平台'),
        ),
        migrations.AlterField(
            model_name='scenariorule',
            name='platform',
            field=models.CharField(blank=True, choices=[('', '所有平台'), ('taobao', '淘宝/千牛'), ('pdd', '拼多多'), ('douyin', '抖音'), ('wechat', '微信')], default='', max_length=20, verbose_name='适用平台'),
        ),
        migrations.AlterField(
            model_name='sensitivewordrule',
            name='platform',
            field=models.CharField(blank=True, choices=[('', '所有平台'), ('taobao', '淘宝/千牛'), ('pdd', '拼多多'), ('douyin', '抖音'), ('wechat', '微信')], default='', max_length=20, verbose_name='适用平台'),
        ),
        migrations.CreateModel(
            name='TokenUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt_tokens', models.IntegerField(default=0, verbose_name='输入Token数')),
                ('completion_tokens', models.IntegerField(default=0, verbose_name='输出Token数')),
                ('total_tokens', models.IntegerField(default=0, verbose_name='总Token数')),
                ('model_name', models.CharField(choices=[('deepseek', 'DeepSeek'), ('qwen', '通义千问'), ('doubao', '豆包'), ('openai', 'OpenAI'), ('gemini', 'Gemini')], db_index=True, default='deepseek', max_length=50, verbose_name='模型平台')),
                ('model_version', models.CharField(blank=True, default='', max_length=100, verbose_name='模型版本')),
                ('request_type', models.CharField(choices=[('chat', '对话回复'), ('vision', '图像识别'), ('qa_generation', 'QA生成')], db_index=True, default='chat', max_length=20, verbose_name='请求类型')),
                ('cost_estimate', models.DecimalField(decimal_places=6, default=0, max_digits=10, verbose_name='预估成本(元)')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('conversation_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='token_usages', to='ai.conversationrecord', verbose_name='关联对话记录')),
                ('shop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='token_usages', to='shops.shop', verbose_name='所属店铺')),
            ],
            options={
                'verbose_name': 'Token使用记录',
                'verbose_name_plural': 'Token使用记录',
                'db_table': 'ai_token_usage',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['shop', 'model_name', 'created_at'], name='ai_token_us_shop_id_c56a72_idx'), models.Index(fields=['model_name', 'created_at'], name='ai_token_us_model_n_297527_idx')],
            },
        ),
    ]
