# Generated by Django 6.0.2 on 2026-02-20 14:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shops', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningTask',
            fields=[
                ('task_id', models.CharField(default=uuid.uuid4, max_length=50, primary_key=True, serialize=False, verbose_name='任务ID')),
                ('platform', models.CharField(help_text='pdd/taobao/douyin', max_length=20, verbose_name='平台')),
                ('status', models.CharField(choices=[('pending', '待处理'), ('running', '进行中'), ('completed', '已完成'), ('failed', '失败')], default='pending', max_length=20, verbose_name='状态')),
                ('total_products', models.IntegerField(default=0, verbose_name='总商品数')),
                ('processed_count', models.IntegerField(default=0, verbose_name='已处理数')),
                ('success_count', models.IntegerField(default=0, verbose_name='成功数')),
                ('fail_count', models.IntegerField(default=0, verbose_name='失败数')),
                ('qa_generated', models.IntegerField(default=0, verbose_name='生成问答数')),
                ('logs', models.JSONField(default=list, verbose_name='日志')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='开始时间')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_tasks', to=settings.AUTH_USER_MODEL, verbose_name='所有者')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_tasks', to='shops.shop', verbose_name='店铺')),
            ],
            options={
                'verbose_name': '学习任务',
                'verbose_name_plural': '学习任务',
                'db_table': 'learning_task',
                'ordering': ['-started_at'],
            },
        ),
    ]
