# Generated by Django 6.0.2 on 2026-02-22 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(db_index=True, max_length=20, verbose_name='版本号')),
                ('platform', models.CharField(choices=[('windows', 'Windows'), ('mac', 'macOS'), ('linux', 'Linux')], default='windows', max_length=20, verbose_name='平台')),
                ('file_name', models.CharField(max_length=255, verbose_name='安装包文件名')),
                ('file_size', models.BigIntegerField(default=0, verbose_name='文件大小(字节)')),
                ('download_url', models.CharField(max_length=500, verbose_name='下载路径')),
                ('checksum_sha512', models.CharField(blank=True, default='', max_length=128, verbose_name='SHA512校验值')),
                ('release_notes', models.TextField(blank=True, default='', verbose_name='更新日志')),
                ('is_latest', models.BooleanField(db_index=True, default=False, verbose_name='是否最新版')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='发布时间')),
                ('download_count', models.IntegerField(default=0, verbose_name='下载次数')),
            ],
            options={
                'verbose_name': '客户端版本',
                'verbose_name_plural': '客户端版本',
                'ordering': ['-created_at'],
                'unique_together': {('version', 'platform')},
            },
        ),
    ]
