# Generated by Django 6.0.2 on 2026-02-20 12:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shops', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(verbose_name='问题')),
                ('answer', models.TextField(verbose_name='回答')),
                ('is_correct', models.BooleanField(default=False, verbose_name='是否正确答案')),
                ('category', models.CharField(blank=True, max_length=50, verbose_name='分类')),
                ('keywords', models.CharField(blank=True, max_length=255, verbose_name='关键词')),
                ('usage_count', models.IntegerField(default=0, verbose_name='使用次数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_items', to=settings.AUTH_USER_MODEL, verbose_name='所有者')),
                ('shop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_items', to='shops.shop', verbose_name='所属店铺')),
            ],
            options={
                'verbose_name': '知识库',
                'verbose_name_plural': '知识库',
                'db_table': 'knowledge_base',
                'ordering': ['-is_correct', '-usage_count', '-created_at'],
                'indexes': [models.Index(fields=['shop', 'is_correct'], name='knowledge_b_shop_id_fdceed_idx'), models.Index(fields=['owner'], name='knowledge_b_owner_i_57ad8e_idx')],
            },
        ),
    ]
