# Generated by Django 6.0.2 on 2026-02-20 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0001_initial'),
        ('products', '0002_product_learned_at_product_learning_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgebase',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='knowledge_items', to='products.product', verbose_name='关联商品'),
        ),
        migrations.AddField(
            model_name='knowledgebase',
            name='source',
            field=models.CharField(choices=[('manual', '手动录入'), ('auto_learned', '自动学习'), ('ai_generated', 'AI生成')], default='manual', max_length=20, verbose_name='来源'),
        ),
    ]
