# Generated by Django 6.0.2 on 2026-02-22 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0002_knowledgebase_product_knowledgebase_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgebase',
            name='embedding_model',
            field=models.CharField(blank=True, max_length=100, verbose_name='向量模型'),
        ),
        migrations.AddField(
            model_name='knowledgebase',
            name='question_embedding',
            field=models.TextField(blank=True, null=True, verbose_name='问题向量'),
        ),
    ]
