# Generated by Django 6.0.2 on 2026-02-20 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shops', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('session_id', models.CharField(editable=False, max_length=50, primary_key=True, serialize=False)),
                ('customer_id', models.CharField(blank=True, max_length=100, verbose_name='客户ID')),
                ('customer_name', models.CharField(blank=True, max_length=100, verbose_name='客户名称')),
                ('platform', models.CharField(blank=True, max_length=50, verbose_name='平台')),
                ('status', models.CharField(choices=[('active', '进行中'), ('closed', '已关闭'), ('archived', '已归档')], default='active', max_length=20, verbose_name='状态')),
                ('last_message', models.TextField(blank=True, verbose_name='最后消息')),
                ('metadata_json', models.JSONField(blank=True, default=dict, verbose_name='元数据')),
                ('message_count', models.IntegerField(default=0, verbose_name='消息数')),
                ('unread_count', models.IntegerField(default=0, verbose_name='未读数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='shops.shop', verbose_name='所属店铺')),
            ],
            options={
                'verbose_name': '聊天会话',
                'verbose_name_plural': '聊天会话',
                'db_table': 'chat_sessions',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('message_id', models.CharField(editable=False, max_length=50, primary_key=True, serialize=False)),
                ('sender_type', models.CharField(choices=[('customer', '客户'), ('agent', '客服'), ('ai', 'AI'), ('system', '系统')], max_length=20, verbose_name='发送者类型')),
                ('sender_id', models.CharField(blank=True, max_length=100, verbose_name='发送者ID')),
                ('sender_name', models.CharField(blank=True, max_length=100, verbose_name='发送者名称')),
                ('content', models.TextField(verbose_name='消息内容')),
                ('message_type', models.CharField(choices=[('text', '文本'), ('image', '图片'), ('file', '文件'), ('order', '订单'), ('product', '商品')], default='text', max_length=20, verbose_name='消息类型')),
                ('status', models.CharField(choices=[('sent', '已发送'), ('delivered', '已送达'), ('read', '已读'), ('failed', '发送失败')], default='sent', max_length=20, verbose_name='状态')),
                ('metadata_json', models.JSONField(blank=True, default=dict, verbose_name='元数据')),
                ('ai_source', models.CharField(blank=True, max_length=50, verbose_name='AI来源')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='时间戳')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.chatsession', verbose_name='所属会话')),
            ],
            options={
                'verbose_name': '消息',
                'verbose_name_plural': '消息',
                'db_table': 'messages',
                'ordering': ['timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='chatsession',
            index=models.Index(fields=['shop', 'status'], name='chat_sessio_shop_id_561389_idx'),
        ),
        migrations.AddIndex(
            model_name='chatsession',
            index=models.Index(fields=['customer_id'], name='chat_sessio_custome_0af429_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['session', 'timestamp'], name='messages_session_f940d1_idx'),
        ),
    ]
