# Generated by Django 6.0.2 on 2026-02-20 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shops', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.CharField(editable=False, max_length=50, primary_key=True, serialize=False)),
                ('sku', models.CharField(blank=True, max_length=100, verbose_name='SKU')),
                ('name', models.CharField(max_length=255, verbose_name='商品名称')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='价格')),
                ('stock', models.IntegerField(default=0, verbose_name='库存')),
                ('status', models.CharField(choices=[('active', '在售'), ('inactive', '下架')], default='active', max_length=20, verbose_name='状态')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('image_url', models.URLField(blank=True, max_length=500, verbose_name='图片URL')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='shops.shop', verbose_name='所属店铺')),
            ],
            options={
                'verbose_name': '商品',
                'verbose_name_plural': '商品',
                'db_table': 'products',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['shop', 'status'], name='products_shop_id_88f5f8_idx'), models.Index(fields=['sku'], name='products_sku_fe2039_idx')],
            },
        ),
    ]
