# Generated by Django 6.0.2 on 2026-02-20 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='learned_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='学习时间'),
        ),
        migrations.AddField(
            model_name='product',
            name='learning_status',
            field=models.CharField(choices=[('pending', '待学习'), ('learned', '已学习'), ('failed', '学习失败')], default='pending', max_length=20, verbose_name='学习状态'),
        ),
        migrations.AddField(
            model_name='product',
            name='platform_product_id',
            field=models.CharField(blank=True, default='', help_text='电商平台原始商品ID', max_length=100, verbose_name='平台商品ID'),
        ),
        migrations.AddField(
            model_name='product',
            name='specs_json',
            field=models.JSONField(blank=True, default=dict, verbose_name='规格参数JSON'),
        ),
    ]
